# Generated by Django 3.0.9 on 2021-01-15 13:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='الكميه')),
                ('date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': ' منتج مستاجر ',
                'verbose_name_plural': 'المنتجات المستأجره',
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(error_messages={'unique': 'عزيزي الموظف يوجد بالفعل منتج بهذا الاسم.'}, max_length=10000, unique=True, verbose_name='اسم المنتج')),
                ('content', models.TextField(blank=True, null=True, verbose_name='الوصف')),
                ('image', models.ImageField(upload_to='Products', verbose_name='صورة المنتج')),
                ('price', models.FloatField(default=0, verbose_name='سعر التاجير لمدة يوم')),
                ('num_in_stock', models.IntegerField(default=0, verbose_name='العدد المتاح في المخزن')),
                ('num_out_stock', models.IntegerField(default=0, verbose_name='العدد المستأجر')),
                ('slug', models.SlugField(blank=True, editable=False, null=True, unique=True)),
                ('active', models.BooleanField(default=False, editable=False, verbose_name='موجود بالمخزن')),
                ('date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'منتج',
                'verbose_name_plural': 'المنتجات',
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.IntegerField(verbose_name='مدة التاجير بالايام')),
                ('from2', models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ بداية التاجير')),
                ('to', models.DateField(default=django.utils.timezone.now, verbose_name='تاريخ نهاية التاجير')),
                ('price', models.FloatField(default=0, verbose_name='اجمالي المبلغ المستحق')),
                ('full_name', models.CharField(max_length=1000, verbose_name='اسم المستأجر ')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='البريد الالكتروني للمستأجر')),
                ('phone', models.CharField(max_length=20, verbose_name='رقم هاتف المستاجر')),
                ('address', models.TextField(verbose_name='عنوان التوصيل للمستاجر')),
                ('content', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('active', models.BooleanField(default=True, verbose_name='عمليه جاريه')),
                ('date', models.DateTimeField(auto_now=True)),
                ('product', models.ManyToManyField(to='app.Order', verbose_name='المنتج الذي سيتم تاجيره')),
            ],
            options={
                'verbose_name': 'عملية تأجير',
                'verbose_name_plural': 'عمليات التأجير',
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='OrderTow',
            fields=[
                ('quantity', models.IntegerField(default=1, verbose_name='الكميه')),
                ('time', models.IntegerField(verbose_name='مدة التاجير بالايام')),
                ('price', models.IntegerField(default=0, verbose_name='المبلغ المستحق')),
                ('full_name', models.CharField(max_length=1000, verbose_name='اسم المستأجر ')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='البريد الالكتروني ')),
                ('phone', models.CharField(max_length=20, verbose_name='رقم الهاتف ')),
                ('address', models.TextField(verbose_name='عنوان التوصيل ')),
                ('content', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='تاريخ الطلب')),
                ('active', models.BooleanField(default=False, editable=False, verbose_name='تم الدفع')),
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='رقم الطلب')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='app.Product', verbose_name='المنتج المطلوب')),
            ],
            options={
                'verbose_name': 'طلب',
                'verbose_name_plural': 'الطلبات',
                'ordering': ('-date',),
            },
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='app.Product', verbose_name='المنتج'),
        ),
    ]
