# Generated by Django 3.0.9 on 2021-01-18 11:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordertow',
            name='active',
        ),
        migrations.RemoveField(
            model_name='ordertow',
            name='address',
        ),
        migrations.RemoveField(
            model_name='ordertow',
            name='content',
        ),
        migrations.RemoveField(
            model_name='ordertow',
            name='email',
        ),
        migrations.RemoveField(
            model_name='ordertow',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='ordertow',
            name='phone',
        ),
        migrations.AddField(
            model_name='ordertow',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Orderr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_code', models.CharField(max_length=20)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('ordered_date', models.DateTimeField()),
                ('full_name', models.CharField(max_length=1000, verbose_name='اسم المستأجر ')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='البريد الالكتروني ')),
                ('phone', models.CharField(max_length=20, verbose_name='رقم الهاتف ')),
                ('address', models.TextField(verbose_name='عنوان التوصيل ')),
                ('content', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('label', models.CharField(choices=[('A', 'قيد الانتظار'), ('B', 'قيد المراجعه'), ('C', 'تم التسليم')], default='A', max_length=1)),
                ('items', models.ManyToManyField(to='app.OrderTow')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
