# Generated by Django 3.0.9 on 2021-01-18 12:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_auto_20210118_1351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordertow',
            name='time',
        ),
        migrations.AlterField(
            model_name='ordertow',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
