# Generated by Django 3.0.9 on 2021-01-18 12:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0003_auto_20210118_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderr',
            name='time',
            field=models.IntegerField(default=0, verbose_name='مدة التاجير بالايام'),
        ),
        migrations.AlterField(
            model_name='orderr',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ordertow',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
