# Generated by Django 3.0.9 on 2021-01-18 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_ordertow_ordered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordertow',
            name='ordered',
        ),
        migrations.AddField(
            model_name='orderr',
            name='ordered',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
