# Generated by Django 3.0.9 on 2021-01-19 10:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0007_ordertow_ordered'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordertow',
            name='time',
            field=models.IntegerField(default=1, verbose_name='مدة لتاجير باليوم'),
        ),
        migrations.AlterField(
            model_name='ordertow',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستأجر'),
        ),
    ]
