# Generated by Django 3.0.9 on 2021-01-20 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20210119_1252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderr',
            name='ref_code',
        ),
        migrations.AlterField(
            model_name='orderr',
            name='id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False, verbose_name='رقم الطلب'),
        ),
    ]
