# Generated by Django 3.0.9 on 2021-01-20 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20210120_1021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderr',
            name='time',
        ),
    ]
