# Generated by Django 3.0.9 on 2021-01-20 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_orderr_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderr',
            name='price',
            field=models.IntegerField(default=0, verbose_name='المبلغ المستحق'),
        ),
        migrations.AlterField(
            model_name='orderr',
            name='ordered',
            field=models.BooleanField(default=False, editable=False, verbose_name='تم تأكيدالطلب'),
        ),
    ]
