# Generated by Django 3.0.9 on 2021-01-20 12:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0011_auto_20210120_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderr',
            name='ordered',
            field=models.BooleanField(default=False, editable=False, verbose_name='تم الدفع'),
        ),
        migrations.AlterField(
            model_name='orderr',
            name='ordered_date',
            field=models.DateTimeField(verbose_name='تاريخ تأكيد الطلب'),
        ),
        migrations.AlterField(
            model_name='orderr',
            name='price',
            field=models.IntegerField(default=0, editable=False, verbose_name='المبلغ المستحق'),
        ),
        migrations.AlterField(
            model_name='orderr',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
        migrations.AlterField(
            model_name='ordertow',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=120)),
                ('order_id', models.CharField(max_length=120)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=100)),
                ('success', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
