# Generated by Django 3.0.9 on 2021-01-20 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20210120_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderr',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
