# Generated by Django 3.0.9 on 2021-01-22 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20210122_1408'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rental',
            name='product',
        ),
        migrations.AddField(
            model_name='rental',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Orderr', verbose_name='الطلب'),
        ),
    ]
