# Generated by Django 3.0.9 on 2021-01-22 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20210122_1415'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rental',
            name='address',
        ),
        migrations.RemoveField(
            model_name='rental',
            name='content',
        ),
        migrations.RemoveField(
            model_name='rental',
            name='email',
        ),
        migrations.RemoveField(
            model_name='rental',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='rental',
            name='phone',
        ),
    ]
